/**
 * Shared inbound-lead attribution.
 *
 * Every lead that arrives from Google Sheets, Meta Lead Ads or Zapier is
 * attributed to a channel and (optionally) a campaign, mirrored into the
 * industry pack pipeline as a pack record, and recorded in lead_conversions
 * so stage progression and revenue can be reported per channel/campaign.
 */
import { getPack } from "@/lib/industry-packs";

type Admin = {
  from: (t: string) => any;
};

export interface InboundLeadInput {
  tenantId: string;
  leadId: string;
  title: string;
  contactName?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  value?: number | null;
  notes?: string | null;
  externalRef?: string | null;
}

export interface ChannelSpec {
  slug: string;
  name: string;
  kind: string;
  groupSlug?: string | null;
  packSlug?: string | null;
}

const slugify = (s: string) =>
  s.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 48) || "channel";

/** Finds a channel by slug for the tenant, creating it on first use. */
export async function ensureChannel(admin: Admin, tenantId: string, spec: ChannelSpec) {
  const { data: existing } = await admin
    .from("lead_channels")
    .select("id, default_group_slug, default_pack_slug")
    .eq("tenant_id", tenantId)
    .eq("slug", spec.slug)
    .maybeSingle();
  if (existing) return existing as { id: string; default_group_slug: string | null; default_pack_slug: string | null };

  const { data: created } = await admin
    .from("lead_channels")
    .insert({
      tenant_id: tenantId,
      name: spec.name,
      slug: spec.slug,
      kind: spec.kind,
      default_group_slug: spec.groupSlug ?? null,
      default_pack_slug: spec.packSlug ?? null,
    })
    .select("id, default_group_slug, default_pack_slug")
    .maybeSingle();
  return (created ?? null) as { id: string; default_group_slug: string | null; default_pack_slug: string | null } | null;
}

/** Finds or creates the campaign a lead was generated by. */
export async function ensureCampaign(
  admin: Admin,
  tenantId: string,
  channelId: string | null,
  name: string | null | undefined,
) {
  if (!name) return null;
  const code = slugify(name);
  const { data: existing } = await admin
    .from("lead_campaigns")
    .select("id")
    .eq("tenant_id", tenantId)
    .eq("code", code)
    .maybeSingle();
  if (existing) return existing as { id: string };
  const { data: created } = await admin
    .from("lead_campaigns")
    .insert({ tenant_id: tenantId, channel_id: channelId, name, code })
    .select("id")
    .maybeSingle();
  return (created ?? null) as { id: string } | null;
}

/**
 * Attributes an already-inserted lead: stamps channel/campaign on the lead,
 * opens a pack pipeline record in the channel's default pack, and writes the
 * conversion row used by the lead-source reports.
 */
export async function trackInboundLead(
  admin: Admin,
  channelSpec: ChannelSpec,
  campaignName: string | null | undefined,
  lead: InboundLeadInput,
) {
  const channel = await ensureChannel(admin, lead.tenantId, channelSpec);
  const channelId = channel?.id ?? null;
  const campaign = await ensureCampaign(admin, lead.tenantId, channelId, campaignName);

  const groupSlug = channelSpec.groupSlug ?? channel?.default_group_slug ?? null;
  const packSlug = channelSpec.packSlug ?? channel?.default_pack_slug ?? null;
  const pack = groupSlug && packSlug ? getPack(groupSlug, packSlug) : undefined;
  const stage = pack?.stages[0] ?? "New";

  let packRecordId: string | null = null;
  if (groupSlug && packSlug) {
    const { data: rec } = await admin
      .from("pack_records")
      .insert({
        tenant_id: lead.tenantId,
        group_slug: groupSlug,
        pack_slug: packSlug,
        title: lead.title,
        stage,
        contact_name: lead.contactName ?? null,
        contact_email: lead.contactEmail ?? null,
        contact_phone: lead.contactPhone ?? null,
        value: lead.value ?? null,
        source: channelSpec.name,
        notes: lead.notes ?? null,
        channel_id: channelId,
        campaign_id: campaign?.id ?? null,
        lead_id: lead.leadId,
      })
      .select("id")
      .maybeSingle();
    packRecordId = (rec as { id: string } | null)?.id ?? null;
  }

  await admin
    .from("leads")
    .update({
      channel_id: channelId,
      campaign_id: campaign?.id ?? null,
      external_ref: lead.externalRef ?? null,
      industry_group: groupSlug,
    })
    .eq("id", lead.leadId);

  await admin.from("lead_conversions").insert({
    tenant_id: lead.tenantId,
    lead_id: lead.leadId,
    pack_record_id: packRecordId,
    channel_id: channelId,
    campaign_id: campaign?.id ?? null,
    industry_group: groupSlug,
    group_slug: groupSlug,
    pack_slug: packSlug,
    stage,
    status: "open",
    revenue: 0,
  });

  return { channelId, campaignId: campaign?.id ?? null, packRecordId, stage };
}
